### ISSUE TITLE
Cannot Run on Fedora 39

### ISSUE THREAD

**Issue by kcfresh53** [CodersCreative/natural-tts#2]
Due to the requirement of Speech Dispatcher v0.7.0, the project cannot effectively be run on modern Fedora distributions or its derivatives. Attempting to run a simple Hello world test will result in the following error:

```
error: failed to run custom build command for `speech-dispatcher-sys v0.7.0`

Caused by:
  process didn't exit successfully: `/home/[user]/Documents/Projects/Rust/HumanInteractionTests/target/debug/build/speech-dispatcher-sys-7bc85cd666e6bccd/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=speechd

  --- stderr
  wrapper.h:1:10: fatal error: 'speech-dispatcher/libspeechd.h' file not found
  thread 'main' panicked at /home/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/speech-dispatcher-sys-0.7.0/build.rs:22:10:
  called `Result::unwrap()` on an `Err` value: ClangDiagnostic("wrapper.h:1:10: fatal error: 'speech-dispatcher/libspeechd.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

Distributions like Fedora and its derivatives are bundled with speech-dispatcher-0.11.5-2 or higher. A potential solution is to increase the Speech Dispatcher version requirement or check for multiple versions.

**Comment by CodersCreative** [comment]
Please try and install this from the official fedora repo : speech-dispatcher-devel. Using: `sudo dnf install speech-dispatcher-devel`

**Comment by kcfresh53** [comment]
This package worked. Thank you.
